services:
 - type: web
   name: app-backend
   runtime: python
   rootDir: .
   buildCommand: pip install -r requirements.txt
   startCommand: python app.py
 - type: web
   name: app-frontend
   runtime: node
   rootDir: frontend
   buildCommand: npm install
   startCommand: npm start
   env_vars:
 - key: BINANCE_IP_WHITELIST
   value: "74.220.48.0,74.220.49.0,74.220.50.0,74.220.51.0,74.220.52.0,74.220.53.0,74.220.54.0,74.220.55.0,74.220.56.0,74.220.57.0,74.220.58.0"
